version: '3.9'

name: sola

services:

  order-service:
    build:
      context: ./order-service
    ports:
      - '9081-9085:8080'
    deploy:
      mode: replicated
      replicas: 5

  shipping-service:
    build:
      context: ./shipping-service
    ports:
      - '9086-9088:8080'
    deploy:
      mode: replicated
      replicas: 3
